# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortIntro', models.TextField()),
                ('hourlyRate', models.IntegerField()),
                ('blackedOutTime', models.DurationField()),
                ('isContracted', models.BooleanField()),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='privateTutor',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='student',
        ),
        migrations.RemoveField(
            model_name='bookingrecord',
            name='cTutor',
        ),
        migrations.RemoveField(
            model_name='bookingrecord',
            name='pTutor',
        ),
        migrations.AlterField(
            model_name='bookingrecord',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Student'),
        ),
        migrations.DeleteModel(
            name='ContractedTutor',
        ),
        migrations.DeleteModel(
            name='PrivateTutor',
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
        migrations.AddField(
            model_name='bookingrecord',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Tutor'),
        ),
    ]
